name:                file-templates
version:             1.0.0.0
synopsis:            Use templates for files and directories
description:
homepage:            https://github.com/anfelor/file-templates#readme
author:              Anton Felix Lorenzen
maintainer:          anfelor@posteo.de
license:             BSD3
copyright:           BSD3
category:            Web

dependencies:       base >= 4.7 && < 5
                  , foundation
                  , directory
                  , attoparsec
                  , filepath
                  , bytestring
                  , unordered-containers
                  , transformers
default-extensions: NoImplicitPrelude
                  , OverloadedStrings

executables:
  new:
    source-dirs:      src
    main:             Main.hs
